apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.castService.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URI: "postgresql://cast_db_username:cast_db_password@{{ .Values.castdb.name }}/cast_db_{{ .Values.namespace }}"
---

