apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.castdb.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: "cast_db_username"
  POSTGRES_PASSWORD: "cast_db_password"
  POSTGRES_DB: "cast_db_{{ .Values.namespace }}"
---
