# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: "{{ .Values.namespace }}.{{ .Values.ingress.host }}"
    http:
      paths:
      - path: /api/v1/movies
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.movieService.name }}
            port:
              number: 8001
  - host: "{{ .Values.namespace }}.{{ .Values.ingress.host }}"
    http:
      paths:
      - path: /api/v1/casts
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.castService.name }}
            port:
              number: 8002
---

