apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.movieService.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URI: "postgresql://movie_db_username:movie_db_password@{{ .Values.moviedb.name }}/movie_db_{{ .Values.namespace }}"
  CAST_SERVICE_HOST_URL: "http://{{ .Values.castService.name }}:{{ .Values.castService.service.port }}/api/v1/casts/"
---

