apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.moviedb.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: "movie_db_username"
  POSTGRES_PASSWORD: "movie_db_password"
  POSTGRES_DB: "movie_db_{{ .Values.namespace }}"
---
